#Fonction qui permet de remplacer les caractères spéciaux
def replaceCaracter(txt, newtxt):
    newChar = txt.replace(txt, newtxt)
    return newChar

#Caractère spéciaux remplacé par espace
#lettre toute seule " a " [a]
replaceCaracter("'", " ")
replaceCaracter("/", " ")
replaceCaracter("#", " ")
replaceCaracter(":", " ")
replaceCaracter("/", " ")
replaceCaracter("!", " ")
replaceCaracter("-", " ")
replaceCaracter("_", " ")
replaceCaracter("~", " ")
replaceCaracter(";", " ")


replaceCaracter(" s ", " [s] ")
replaceCaracter(" m ", " [m] ")
replaceCaracter(" t ", " [t] ")
replaceCaracter(" j ", " [j] ")
replaceCaracter(" l ", " [l] ")
replaceCaracter(" d ", " [d] ")

replaceCaracter(" comment ", " [comment] ") #txt.replace(",", "") remplace comment par un vide
replaceCaracter(" quoi ", " [quoi] ")
replaceCaracter(" qui ", " [qui] ")
replaceCaracter(" du ", " [du] ")
replaceCaracter(" de ", " [de] ")
replaceCaracter(" des ", " [des] ")
replaceCaracter(" la ", " [la] ")
replaceCaracter(" le ", " [le] ")
replaceCaracter(" les ", " [les] ")
replaceCaracter(" à ", " [a] ")
replaceCaracter(" quel ", " [quel] ")
replaceCaracter(" quels ", " [quels] ")
replaceCaracter(" quelle ", " [quelle] ")
replaceCaracter(" quelles ", " [quelles] ")
replaceCaracter(" a ", " [a] ")
replaceCaracter(" je ", " [je] ")
replaceCaracter(" tu ", " [tu] ")
replaceCaracter(" il ", " [il] ")
replaceCaracter(" elle ", " [elle] ")
replaceCaracter(" nous ", " [nous] ")
replaceCaracter(" vous ", " [vous] ")
replaceCaracter(" ils ", " [ils] ")
replaceCaracter(" elles ", " [elles] ")
replaceCaracter(" mais ", " [mais] ")
replaceCaracter(" car ", " [car] ")
replaceCaracter(" et ", " [et] ")
replaceCaracter(" donc ", " [donc] ")
replaceCaracter(" ni ", " [ni] ")
replaceCaracter(" ou ", " [ou] ")
replaceCaracter(" ni ", " [ni] ")
replaceCaracter(" car ", " [car] ")
replaceCaracter(" or ", " [or] ")
replaceCaracter(" comme ", " [comme] ")
replaceCaracter(" lorsque ", " [lorsque] ")
replaceCaracter(" puisque ", " [puisque] ")
replaceCaracter(" quand ", " [quand] ")
replaceCaracter(" si ", " [si] ")
replaceCaracter(" ce ", " [ce] ")
replaceCaracter(" ces ", " [ces] ")
replaceCaracter(" cette ", " [cette] ")
replaceCaracter(" cet ", " [cet] ")
replaceCaracter(" un ", " [une] ")
replaceCaracter(" mon ", " [mon] ")
replaceCaracter(" ton ", " [ton] ")
replaceCaracter(" son ", " [son] ")
replaceCaracter(" notre ", " [notre] ")
replaceCaracter(" votre ", " [votre] ")
replaceCaracter(" leur ", " [leur] ")
replaceCaracter(" ma ", " [ma] ")
replaceCaracter(" ta ", " [ta] ")
replaceCaracter(" sa ", " [sa] ")
replaceCaracter(" mes ", " [mes] ")
replaceCaracter(" tes ", " [tes] ")
replaceCaracter(" ses ", " [ses] ")


