def replaceMultiple(mainString, toBeReplaces, newString):
    # Iterate over the strings to be replaced
    for elem in toBeReplaces:
        # Check if string is in the main string
        if elem in mainString:
            # Replace the string
            mainString = mainString.replace(elem, newString)

    return mainString

def replaceCharacters(mainStr):
    modifOne = replaceMultiple(mainStr, ["/", "#", ":", "/", "-", "!", "_", "@", ";", "~", "'"], " ")
    modifTwo = replaceMultiple(modifOne, [" s "], " [s] ")
    modifThree = replaceMultiple(modifTwo, [" m "], " [m] ")
    modifFour = replaceMultiple(modifThree, [" t "], " [t] ")
    modifFive = replaceMultiple(modifFour, [" j "], " [j] ")
    modifSix = replaceMultiple(modifFive, [" l "], " [l] ")
    modifSeven = replaceMultiple(modifSix, [" d "], " [d] ")
    modifEight = replaceMultiple(modifSeven, [" comment "], " [comment] ")
    modifNine = replaceMultiple(modifEight, [" quoi "], " [quoi] ")
    modifTen = replaceMultiple(modifNine, [" qui "], " [qui] ")
    modifEleven = replaceMultiple(modifTen, [" du "], " [du] ")
    modifTwelve = replaceMultiple(modifEleven, [" de "], " [de] ")
    modifThirteen = replaceMultiple(modifTwelve, [" des "], " [des] ")
    modifFourteen = replaceMultiple(modifThirteen, [" la "], " [la] ")
    modifFifteen = replaceMultiple(modifFourteen, [" le "], " [le] ")
    modifSixteen = replaceMultiple(modifFifteen, [" les "], " [les] ")

    modifSeventeen = replaceMultiple(modifSixteen,[" à "], " [a] ")
    modifEighteen = replaceMultiple(modifSeventeen,[" quel "], " [quel] ")
    modifNineteen = replaceMultiple(modifEighteen,[" quels "], " [quels] ")
    modifTwenty = replaceMultiple(modifNineteen,[" quelle "], " [quelle] ")
    modifTwentyOne = replaceMultiple(modifTwenty,[" quelles "], " [quelles] ")
    modifTwentyTwo = replaceMultiple(modifTwentyOne,[" a "], " [a] ")
    modifTwentyThree = replaceMultiple(modifTwentyTwo,[" je "], " [je] ")
    modifTwentyFour = replaceMultiple(modifTwentyThree,[" tu "], " [tu] ")
    modifTwentyFive = replaceMultiple(modifTwentyFour,[" il "], " [il] ")
    modifTwentySix = replaceMultiple(modifTwentyFive,[" elle "], " [elle] ")
    modifTwentySeven = replaceMultiple(modifTwentySix,[" nous "], " [nous] ")
    modifTwentyEight = replaceMultiple(modifTwentySeven,[" vous "], " [vous] ")
    modifTwentyNine = replaceMultiple(modifTwentyEight,[" ils "], " [ils] ")
    modufThirty = replaceMultiple(modifTwentyNine,[" elles "], " [elles] ")
    modifThirtyOne = replaceMultiple(modufThirty,[" mais "], " [mais] ")
    modifThirtyTwo = replaceMultiple(modifThirtyOne,[" car "], " [car] ")
    modifThirtyThree = replaceMultiple(modifThirtyTwo,[" et "], " [et] ")
    modifThirtyFour = replaceMultiple(modifThirtyThree,[" donc "], " [donc] ")
    modifThirtyFive = replaceMultiple(modifThirtyFour,[" ni "], " [ni] ")
    modifThirtySix = replaceMultiple(modifThirtyFive,[" ou "], " [ou] ")
    modifThirtySeven = replaceMultiple(modifThirtySix,[" car "], " [car] ")
    modifThurtyEight = replaceMultiple(modifThirtySeven,[" or "], " [or] ")
    modifThirtyNine = replaceMultiple(modifThurtyEight,[" comme "], " [comme] ")
    modifFourty = replaceMultiple(modifThirtyNine,[" lorsque "], " [lorsque] ")
    modifFourtyOne = replaceMultiple(modifFourty,[" puisque "], " [puisque] ")
    modifFourtyTwo = replaceMultiple(modifFourtyOne,[" quand "], " [quand] ")
    modifFourtyThree = replaceMultiple(modifFourtyTwo,[" si "], " [si] ")
    modifFourtyFour = replaceMultiple(modifFourtyThree,[" ce "], " [ce] ")
    modifFourtyFive = replaceMultiple(modifFourtyFour,[" ces "], " [ces] ")
    modifFourtySix = replaceMultiple(modifFourtyFive,[" cette "], " [cette] ")
    modifFourtySeven = replaceMultiple(modifFourtySix,[" cet "], " [cet] ")
    modifFourtyEight = replaceMultiple(modifFourtySeven,[" un "], " [une] ")
    modifFourtyNine = replaceMultiple(modifFourtyEight,[" mon "], " [mon] ")
    modifFifty = replaceMultiple(modifFourtyNine,[" ton "], " [ton] ")
    modifFiftyOne = replaceMultiple(modifFifty,[" son "], " [son] ")
    modifFiftyTwo = replaceMultiple(modifFiftyOne,[" notre "], " [notre] ")
    modifFiftyThree = replaceMultiple(modifFiftyTwo,[" votre "], " [votre] ")
    modifFiftyFour = replaceMultiple(modifFiftyThree,[" leur "], " [leur] ")
    modifFiftyFive = replaceMultiple(modifFiftyFour,[" ma "], " [ma] ")
    modifFiftySix = replaceMultiple(modifFiftyFive,[" ta "], " [ta] ")
    modifFiftySeven = replaceMultiple(modifFiftySix,[" sa "], " [sa] ")
    modifFiftyEight = replaceMultiple(modifFiftySeven,[" mes "], " [mes] ")
    modifFiftyNine = replaceMultiple(modifFiftyEight,[" tes "], " [tes] ")
    modifSixty = replaceMultiple(modifFiftyNine,[" ses "], " [ses] ")
    print(modifSixty)

replaceCharacters("Hello, This i's a sample string")